# general settings
name: gcfsr_scale4to16_ffhq512
model_type: GCFSR_Model
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: FFHQ
    type: FFHQ_control_Dataset
    dataroot_gt: /kaggle/input/flickrfaceshq-dataset-ffhq
    io_backend:
      type: disk
    
    downsample_list: [16, 16, 16, 16, 8, 8, 4, 4, 2, 2]
    cond_norm: 16.

    use_hflip: true
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 6
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    # Please modify accordingly to use your own validation
    # Or comment the val block if do not need validation during training
    name: validation
    type: SingleImage_GT_Dataset
    dataroot_lq: /kaggle/input/celeba-512-1000-val/celebaHQ_512_1000
    out_size: 512
    io_backend:
      type: disk
    cond_norm: 16.
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]
    scale: 1

# network structures
network_g:
  type: GCFSR
  out_size: 512
  num_style_feat: 256
  channel_multiplier: 1
  narrow: 1

network_d:
  type: StyleGAN2Discriminator_no_std
  out_size: 512
  channel_multiplier: 1
  resample_kernel: [1, 3, 3, 1]

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  pretrain_network_d: ~
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-3

  optim_d:
    type: Adam
    lr: !!float 2e-3

  scheduler:
    type: MultiStepLR
    milestones: [800000]
    gamma: 0.5

  total_iter: 80000
  warmup_iter: -1  # no warm up

  # losses
  gan_opt:
    type: GANLoss
    gan_type: wgan_softplus
    loss_weight: !!float 1e-2

  pixel_opt:
    type: L1Loss
    loss_weight: !!float 1
    reduction: mean
  
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv4_3': 1  # before relu
    vgg_type: vgg16
    use_input_norm: true
    range_norm: true
    perceptual_weight: !!float 1e-2
    style_weight: 0
    criterion: l1
  
  embedding_opt:
    type: EmbeddingLoss
    pretrained: vggface2
    embedding_weight: !!float 1e-2
    criterion: l1

  # r1 regularization for discriminator
  r1_reg_weight: 10
  # path length regularization for generator
  path_batch_shrink: 2
  path_reg_weight: 2

  net_g_reg_every: 4
  net_d_reg_every: 16
  mixing_prob: 0.9

  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  val_freq: 5000
  save_img: true
  num_val_samples: 3

# logging settings
logger:
  print_freq: 50
  save_checkpoint_freq: 1000
  use_tb_logger: true
  wandb:
    project: gcfsr_base_512
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: false
